### ISSUE TITLE
请问有计划出pdf格式的文档吗？

### ISSUE THREAD

**Issue by Aincvy** [jsksxs360/How-to-use-Transformers#11]

**Comment by jsksxs360** [comment]
你好，这个教程以代码为主，文档格式不太便于展示，所以暂时没有计划出文档。

**Comment by Aincvy** [comment]
https://transformers.run/back/nlp/       这里的内容也不打算出一个pdf 的文档吗？  还是说我找错地方了？ 

我现在是用打印的方式 保存成pdf 文档。      只不过一次只能打印一个页面 - -  

准备放到dpt rp1 上阅读的， 是一个A4纸大小的墨水屏

**Comment by jsksxs360** [comment]
你好，这一部分是四五年之前写的，可能已经过时了[捂脸]。
PDF文档等我更新内容之后再说吧。

**Comment by Aincvy** [comment]
OK， 了解
