### ISSUE TITLE
2，3章疑问

### ISSUE THREAD

**Issue by codecason** [jsksxs360/How-to-use-Transformers#24]
第2章
![image](https://github.com/jsksxs360/How-to-use-Transformers/assets/25704113/c227cb8c-5fb1-451c-a1f3-39b7e3fd16f8)
输入这里应该是input embeddings吧？

第3章
![image](https://github.com/jsksxs360/How-to-use-Transformers/assets/25704113/77f8790f-7779-46f3-8450-78b342bf82dd)

公式5的求和上标是不是应该为n?

**Comment by jsksxs360** [comment]
你好，非常感谢指出问题！已经都修正了

谢谢！

**Comment by codecason** [comment]
已解决，关闭
