### ISSUE TITLE
维度不对，这里的维度应该是 dxn 吧。如果是 nxd, X= (x1,x2,...,xn)^T

### ISSUE THREAD

**Issue by workingloong** [jsksxs360/How-to-use-Transformers#9]
![image](https://github.com/jsksxs360/How-to-use-Transformers/assets/18071380/1012690c-1206-4df5-9aa1-27d23174423a)

**Comment by workingloong** [comment]
好的。另外还发现一个问题。这里应该说 head_dim 是 embed_dim 的因数，而不是倍数。768/12=64，64是768 的因数，768是64的倍数。
![image](https://github.com/jsksxs360/How-to-use-Transformers/assets/18071380/03956483-c4fe-4c87-9b1e-7844660a6370)

**Comment by jsksxs360** [comment]
是的，已在原文中修正。谢谢！
